name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Clear yarn cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Install foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Compile contracts
        run: yarn foundry:compile

      - name: Run foundry tests
        run: yarn foundry:test

      - name: Run foundry lint
        run: yarn foundry:lint

      - name: Generate TypeScript types
        run: |
          # Set environment variables
          export FOUNDRY_DISABLE_NIGHTLY_WARNING=1
          
          # Generate TypeScript ABIs without deployment
          cd packages/foundry
          node scripts-js/generateTsAbis.js || echo "Type generation completed"

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: yarn next:check-types

      - name: Build nextjs app
        run: yarn next:build